---
apiVersion: registry.apicur.io/v1
kind: ApicurioRegistry3
metadata:
  name: apicurio-registry
  namespace: kafka
spec:
  app:
    storage:
      type: kafkasql
      kafkasql:
        bootstrapServers: kafka-cluster-kafka-bootstrap.kafka:9092
    replicas: 2
    # resources:
    #   requests:
    #     cpu: 250m
    #     memory: 384Mi
    #   limits:
    #     cpu: 1000m
    #     memory: 768Mi
