---
replicaCount: 2

image:
  tag: "3.2.4"

kafkasql:
  bootstrapServers: "kafka-cluster-kafka-bootstrap.kafka:9092"

extraEnv:
  - name: APICURIO_KAFKASQL_TOPIC_REPLICATION_FACTOR
    value: "3"

resources:
  requests:
    cpu: 250m
    memory: 384Mi
  limits:
    cpu: 1000m
    memory: 768Mi

ingress:
  enabled: true
  className: kong
  hosts:
    - host: schema-registry.127-0-0-1.nip.io
      paths:
        - path: /
          pathType: Prefix
