apiVersion: v1
kind: Namespace
metadata:
  name: ingress-haproxy
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: haproxy
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  controller: haproxy-ingress.github.io/controller
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: haproxy-ingress
  namespace: kube-system
spec:
  chart: haproxy-ingress
  repo: https://haproxy-ingress.github.io/charts
  targetNamespace: ingress-haproxy
  version: 0.14.7
  valuesContent: |-
    controller:
      ingressClass: haproxy
      publishService:
        enabled: true
      config:
        use-forwarded-headers: "true"
