---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-secret
  namespace: test
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: k8s-secret
    template:
      data:
        test1: "{{ .fha | b64enc }}"
        test2: "{{ .phk | toString }}"
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: supersecret
# ---
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: example-secret2
#   namespace: test
# spec:
#   refreshInterval: 1m
#   secretStoreRef:
#     name: vault-backend
#     kind: ClusterSecretStore
#   target:
#     name: k8s-secret2
#     creationPolicy: Owner
#   dataFrom:
#   - extract:
#       key: common
#   - extract:
#       key: supersecret
