apiVersion: gateway.networking.k8s.io/v1
kind: TLSRoute
metadata:
  name: httpbin-tls
  namespace: demo
spec:
  parentRefs:
  - name: kong
    namespace: kong
    kind: Gateway
    sectionName: kong-tls-passthrough
  hostnames:
  - httpbin-tls.example.com
  rules:
  - backendRefs:
    - name: tls-backend
      port: 443
