controller:
  ingressController:
    env:
      log_level: debug
      feature_gates: "GatewayAlpha=true"
    adminApi:
      tls:
        client:
          enabled: true
      repository: kong/kubernetes-ingress-controller
      tag: 3.5.6

gateway:
  env:
    log_level: debug
    admin_gui_url: https://kong-manager.example.com:8081
    admin_api_uri: https://kong-admin.example.com:8081


  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 2
  image:
    repository: kong/kong-gateway
    tag: 3.13.0.2
  serviceMonitor:
    enabled: true
    labels:
      release: promstack

  proxy:
    type: LoadBalancer
    stream:
      - containerPort: 9443
        servicePort: 9443
        protocol: TCP
        parameters:
          - ssl

  manager:
    enabled: true
    type: ClusterIP
    http:
      enabled: true

  admin:
    enabled: true
    type: ClusterIP
    http:
      enabled: true
