apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: webui-oidc
  namespace: ai-platform
plugin: openid-connect
config:
  issuer: "http://keycloak.ai-platform.svc.cluster.local:8080/realms/ai-platform/.well-known/openid-configuration"
  client_id:
    - "kong-ai-gateway"
  client_secret:
    - "kong-ai-gateway-secret"
  redirect_uri:
    - "https://chat.example.com:8081/callback"
  scopes:
    - openid
    - profile
    - email
  auth_methods:
    - authorization_code
  login_redirect_mode: query
  logout_redirect_uri:
    - "https://chat.example.com:8081"
  token_endpoint: "http://keycloak.ai-platform.svc.cluster.local:8080/realms/ai-platform/protocol/openid-connect/token"
  authorization_endpoint: "https://keycloak.example.com:8081/realms/ai-platform/protocol/openid-connect/auth"
  end_session_endpoint: "https://keycloak.example.com:8081/realms/ai-platform/protocol/openid-connect/logout"
  extra_jwks_uris:
    - "http://keycloak.ai-platform.svc.cluster.local:8080/realms/ai-platform/protocol/openid-connect/certs"
