apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: ai-proxy-gemma
  namespace: kong
plugin: ai-proxy
config:
  route_type: "llm/v1/chat"
  model:
    provider: openai
    name: gemma3:1b
    options:
      upstream_url: "http://ollama.ai-platform.svc.cluster.local:11434/v1/chat/completions"
      input_cost: 500
      output_cost: 1500
