---
replicaCount: 1

yamlApplicationConfig:
  kafka:
    clusters:
      - name: kafka-cluster
        bootstrapServers: kafka-cluster-kafka-bootstrap.kafka:9092
        schemaRegistry: http://apicurio-registry-app-service.kafka:8080/apis/ccompat/v7
        schemaRegistryType: APICURIO
        kafkaConnect:
          - name: kafka-bridge
            address: http://kafka-bridge-bridge-service.kafka:8080
  auth:
    type: disabled
  management:
    health:
      ldap:
        enabled: false

ingress:
  enabled: true
  ingressClassName: kong
  host: kafka-ui.127-0-0-1.nip.io
  path: /
  port:
    number: 80

resources:
  limits:
  #   cpu: 200m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi
