---
injector:
  enabled: false
server:
  ingress:
    enabled: true
    ingressClassName: "haproxy"
    annotations:
      cert-manager.io/cluster-issuer: "openbao-issuer"
      cert-manager.io/common-name: "openbao.example.com"
    hosts:
      - host: openbao.example.com
        paths: []
    tls:
      - hosts:
          - openbao.example.com
        secretName: openbao-tls-secret
  statefulSet:
    securityContext:
      container:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        seccompProfile:
          type: "RuntimeDefault"
