apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpbin
  namespace: demo
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/issuer: "vault-issuer"
    cert-manager.io/common-name: "httpbin.127-0-0-1.nip.io"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - httpbin.127-0-0-1.nip.io
    secretName: httpbin-tls-secret
  rules:
  - host: httpbin.127-0-0-1.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: httpbin
            port:
              number: 80
